services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: npm-app
    environment:
      - NODE_ENV=production
    volumes:
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge